from vardautomation.language import Lang

ARABIC = Lang.make('ar')
CHINESE = Lang.make('zh')
DUTCH = Lang.make('nl')
ENGLISH = Lang.make('en')
FRENCH = Lang.make('fr')
GERMAN = Lang.make('de')
HEBREW = Lang.make('he')
HINDI = Lang.make('hi')
INDONESIAN = Lang.make('id')
ITALIAN = Lang.make('it')
JAPANESE = Lang.make('ja')
KOREAN = Lang.make('ko')
POLISH = Lang.make('pl')
PORTUGUESE = Lang.make('pt')
SPANISH = Lang.make('es')
TAMIL = Lang.make('ta')
TURKISH = Lang.make('tr')
UNDEFINED = Lang.make(None)
