from _typeshed import Incomplete
from html5lib.treebuilders import _base
from lxml import etree as etree, html as html

class DocumentType:
    name: Incomplete
    publicId: Incomplete
    systemId: Incomplete
    def __init__(self, name, publicId, systemId) -> None: ...

class Document:
    childNodes: Incomplete
    def __init__(self) -> None: ...
    def appendChild(self, element) -> None: ...

class TreeBuilder(_base.TreeBuilder):
    documentClass: Incomplete
    doctypeClass: Incomplete
    elementClass: Incomplete
    commentClass: Incomplete
    fragmentClass: Incomplete
    def __init__(self, *args, **kwargs) -> None: ...
    rootInserted: bool
    initialComments: Incomplete
    doctype: Incomplete
    def reset(self) -> None: ...
    def getDocument(self): ...
    def getFragment(self): ...
    def insertDoctype(self, name, publicId, systemId) -> None: ...
    def insertComment(self, data, parent: Incomplete | None = ...) -> None: ...
    document: Incomplete
    def insertRoot(self, name) -> None: ...
