import abc
from _typeshed import Incomplete
from collections import MutableSet

class SetMixin(MutableSet, metaclass=abc.ABCMeta):
    def __len__(self): ...
    def __contains__(self, item): ...
    issubset: Incomplete
    issuperset: Incomplete
    union: Incomplete
    intersection: Incomplete
    difference: Incomplete
    symmetric_difference: Incomplete
    def copy(self): ...
    def update(self, other) -> None: ...
    def intersection_update(self, other) -> None: ...
    def difference_update(self, other) -> None: ...
    def symmetric_difference_update(self, other) -> None: ...
    def discard(self, item) -> None: ...
