from _typeshed import Incomplete
from lxml.builder import ElementMaker as ElementMaker
from lxml.html import html_parser as html_parser

E: Incomplete
A: Incomplete
ABBR: Incomplete
ACRONYM: Incomplete
ADDRESS: Incomplete
APPLET: Incomplete
AREA: Incomplete
B: Incomplete
BASE: Incomplete
BASEFONT: Incomplete
BDO: Incomplete
BIG: Incomplete
BLOCKQUOTE: Incomplete
BODY: Incomplete
BR: Incomplete
BUTTON: Incomplete
CAPTION: Incomplete
CENTER: Incomplete
CITE: Incomplete
CODE: Incomplete
COL: Incomplete
COLGROUP: Incomplete
DD: Incomplete
DEL: Incomplete
DFN: Incomplete
DIR: Incomplete
DIV: Incomplete
DL: Incomplete
DT: Incomplete
EM: Incomplete
FIELDSET: Incomplete
FONT: Incomplete
FORM: Incomplete
FRAME: Incomplete
FRAMESET: Incomplete
H1: Incomplete
H2: Incomplete
H3: Incomplete
H4: Incomplete
H5: Incomplete
H6: Incomplete
HEAD: Incomplete
HR: Incomplete
HTML: Incomplete
I: Incomplete
IFRAME: Incomplete
IMG: Incomplete
INPUT: Incomplete
INS: Incomplete
ISINDEX: Incomplete
KBD: Incomplete
LABEL: Incomplete
LEGEND: Incomplete
LI: Incomplete
LINK: Incomplete
MAP: Incomplete
MENU: Incomplete
META: Incomplete
NOFRAMES: Incomplete
NOSCRIPT: Incomplete
OBJECT: Incomplete
OL: Incomplete
OPTGROUP: Incomplete
OPTION: Incomplete
P: Incomplete
PARAM: Incomplete
PRE: Incomplete
Q: Incomplete
S: Incomplete
SAMP: Incomplete
SCRIPT: Incomplete
SELECT: Incomplete
SMALL: Incomplete
SPAN: Incomplete
STRIKE: Incomplete
STRONG: Incomplete
STYLE: Incomplete
SUB: Incomplete
SUP: Incomplete
TABLE: Incomplete
TBODY: Incomplete
TD: Incomplete
TEXTAREA: Incomplete
TFOOT: Incomplete
TH: Incomplete
THEAD: Incomplete
TITLE: Incomplete
TR: Incomplete
TT: Incomplete
U: Incomplete
UL: Incomplete
VAR: Incomplete
ATTR = dict

def CLASS(v): ...
def FOR(v): ...
