import difflib
from _typeshed import Incomplete

basestring = str

def html_annotate(doclist, markup=...): ...
def htmldiff(old_html, new_html): ...

class DEL_START: ...
class DEL_END: ...
class NoDeletes(Exception): ...

class token(_unicode):
    hide_when_equal: bool
    def __new__(cls, text, pre_tags: Incomplete | None = ..., post_tags: Incomplete | None = ..., trailing_whitespace: str = ...): ...
    def html(self): ...

class tag_token(token):
    def __new__(cls, tag, data, html_repr, pre_tags: Incomplete | None = ..., post_tags: Incomplete | None = ..., trailing_whitespace: str = ...): ...
    def html(self): ...

class href_token(token):
    hide_when_equal: bool
    def html(self): ...

class InsensitiveSequenceMatcher(difflib.SequenceMatcher):
    threshold: int
    def get_matching_blocks(self): ...
