from _typeshed import Incomplete
from html5lib import HTMLParser as _HTMLParser, XHTMLParser as _XHTMLParser
from lxml import etree as etree
from lxml.html import Element as Element, XHTML_NAMESPACE as XHTML_NAMESPACE

class HTMLParser(_HTMLParser):
    def __init__(self, strict: bool = ..., **kwargs) -> None: ...

class XHTMLParser(_XHTMLParser):
    def __init__(self, strict: bool = ..., **kwargs) -> None: ...

xhtml_parser: Incomplete

def document_fromstring(html, guess_charset: Incomplete | None = ..., parser: Incomplete | None = ...): ...
def fragments_fromstring(html, no_leading_text: bool = ..., guess_charset: Incomplete | None = ..., parser: Incomplete | None = ...): ...
def fragment_fromstring(html, create_parent: bool = ..., guess_charset: Incomplete | None = ..., parser: Incomplete | None = ...): ...
def fromstring(html, guess_charset: Incomplete | None = ..., parser: Incomplete | None = ...): ...
def parse(filename_url_or_file, guess_charset: Incomplete | None = ..., parser: Incomplete | None = ...): ...

html_parser: Incomplete
