from _typeshed import Incomplete

def fromstring(data, beautifulsoup: Incomplete | None = ..., makeelement: Incomplete | None = ..., **bsargs): ...
def parse(file, beautifulsoup: Incomplete | None = ..., makeelement: Incomplete | None = ..., **bsargs): ...
def convert_tree(beautiful_soup_tree, makeelement: Incomplete | None = ...): ...

class _PseudoTag:
    name: str
    attrs: Incomplete
    contents: Incomplete
    def __init__(self, contents) -> None: ...
    def __iter__(self): ...
unichr = chr
