import doctest
from _typeshed import Incomplete

PARSE_HTML: Incomplete
PARSE_XML: Incomplete
NOPARSE_MARKUP: Incomplete
OutputChecker = doctest.OutputChecker

class LXMLOutputChecker(OutputChecker):
    empty_tags: Incomplete
    def get_default_parser(self): ...
    def check_output(self, want, got, optionflags): ...
    def get_parser(self, want, got, optionflags): ...
    def compare_docs(self, want, got): ...
    def text_compare(self, want, got, strip): ...
    def tag_compare(self, want, got): ...
    def output_difference(self, example, got, optionflags): ...
    def html_empty_tag(self, el, html: bool = ...): ...
    def format_doc(self, doc, html, indent, prefix: str = ...): ...
    def format_text(self, text, strip: bool = ...): ...
    def format_tag(self, el): ...
    def format_end_tag(self, el): ...
    def collect_diff(self, want, got, html, indent): ...
    def collect_diff_tag(self, want, got): ...
    def collect_diff_end_tag(self, want, got): ...
    def collect_diff_text(self, want, got, strip: bool = ...): ...

class LHTMLOutputChecker(LXMLOutputChecker):
    def get_default_parser(self): ...

def install(html: bool = ...) -> None: ...
def temp_install(html: bool = ..., del_module: Incomplete | None = ...) -> None: ...

class _RestoreChecker:
    dt_self: Incomplete
    checker: Incomplete
    check_func: Incomplete
    clone_func: Incomplete
    del_module: Incomplete
    def __init__(self, dt_self, old_checker, new_checker, check_func, clone_func, del_module) -> None: ...
    func_code: Incomplete
    func_globals: Incomplete
    def install_clone(self) -> None: ...
    def uninstall_clone(self) -> None: ...
    prev_func: Incomplete
    def install_dt_self(self) -> None: ...
    def uninstall_dt_self(self) -> None: ...
    def uninstall_module(self) -> None: ...
    def __call__(self, *args, **kw): ...
    def call_super(self, *args, **kw): ...
