from _typeshed import Incomplete
from ctypes import windll as windll

__version_info__: Incomplete
PY3: Incomplete
unicode = str
system: Incomplete

def user_data_dir(appname: Incomplete | None = ..., appauthor: Incomplete | None = ..., version: Incomplete | None = ..., roaming: bool = ...): ...
def site_data_dir(appname: Incomplete | None = ..., appauthor: Incomplete | None = ..., version: Incomplete | None = ..., multipath: bool = ...): ...
def user_config_dir(appname: Incomplete | None = ..., appauthor: Incomplete | None = ..., version: Incomplete | None = ..., roaming: bool = ...): ...
def site_config_dir(appname: Incomplete | None = ..., appauthor: Incomplete | None = ..., version: Incomplete | None = ..., multipath: bool = ...): ...
def user_cache_dir(appname: Incomplete | None = ..., appauthor: Incomplete | None = ..., version: Incomplete | None = ..., opinion: bool = ...): ...
def user_state_dir(appname: Incomplete | None = ..., appauthor: Incomplete | None = ..., version: Incomplete | None = ..., roaming: bool = ...): ...
def user_log_dir(appname: Incomplete | None = ..., appauthor: Incomplete | None = ..., version: Incomplete | None = ..., opinion: bool = ...): ...

class AppDirs:
    appname: Incomplete
    appauthor: Incomplete
    version: Incomplete
    roaming: Incomplete
    multipath: Incomplete
    def __init__(self, appname: Incomplete | None = ..., appauthor: Incomplete | None = ..., version: Incomplete | None = ..., roaming: bool = ..., multipath: bool = ...) -> None: ...
    @property
    def user_data_dir(self): ...
    @property
    def site_data_dir(self): ...
    @property
    def user_config_dir(self): ...
    @property
    def site_config_dir(self): ...
    @property
    def user_cache_dir(self): ...
    @property
    def user_state_dir(self): ...
    @property
    def user_log_dir(self): ...
