name: lint

on: [push, pull_request]

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Setup Python 3.10
              uses: actions/setup-python@v3
              with:
                  python-version: "3.10"
            - name: Install VapourSynth
              uses: Irrational-Encoding-Wizardry/install-vapoursynth-action@v0.1
              with:
                  version: latest
                  cache: true
            - name: Install dependencies
              id: dependencies
              run: |
                  python3 -m pip install --upgrade pip
                  pip install -r requirements-dev.txt
                  pip install .
            - name: Running flake8
              run: flake8 vsencode
            - name: Running mypy
              if: steps.dependencies.outcome == 'success'
              run: mypy -p vsencode
